name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    name: Deploy Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name:  Install dependencies
        run: npm ci
      - name: Build
        run: tsc
      - name: Docker --- Login to Registry
        uses: docker/login-action@v1
        with:
          registry: registry.l5w.de
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker --- Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.l5w.de/ostfalia-mensa-bot:latest
          context: .
